<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerPpku3ga\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpku3ga/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPpku3ga.legacy');
=======
if (\class_exists(\ContainerOyulxCZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOyulxCZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOyulxCZ.legacy');
>>>>>>> origin

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerPpku3ga\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPpku3ga\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ppku3ga',
    'container.build_id' => '897a17a4',
    'container.build_time' => 1533223492,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpku3ga');
=======
    \class_alias(\ContainerOyulxCZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOyulxCZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OyulxCZ',
    'container.build_id' => 'd028b096',
    'container.build_time' => 1535823433,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOyulxCZ');
>>>>>>> origin
