<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xMzNNK\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xMzNNK/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7xMzNNK.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7xMzNNK\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7xMzNNK\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7xMzNNK',
    'container.build_id' => 'f6f60b19',
    'container.build_time' => 1531922700,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7xMzNNK');
