<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNloKxP9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNloKxP9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNloKxP9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNloKxP9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNloKxP9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NloKxP9',
    'container.build_id' => '661fa3b7',
    'container.build_time' => 1532130670,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNloKxP9');
