<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EVv_ldj' shared service.

return $this->privates['.service_locator.EVv_ldj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('JourEntity' => function (): \App\Entity\Jour {
    return ($this->privates['.errored..service_locator.EVv_ldj.App\Entity\Jour'] ?? $this->load('getJourService.php'));
}));
