<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::ajouterSalle' => function () {
    return ($this->privates['.service_locator.EVv_ldj'] ?? $this->load('get_ServiceLocator_EVvLdjService.php'));
}, 'App\\Controller\\FrontController::partagerSalle' => function () {
    return ($this->privates['.service_locator.FngfaY1'] ?? $this->load('get_ServiceLocator_FngfaY1Service.php'));
}, 'App\\Controller\\RegistrationController::registerAction' => function () {
    return ($this->privates['.service_locator.JPXreA6'] ?? $this->load('get_ServiceLocator_JPXreA6Service.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.UlhrRhb'] ?? $this->load('get_ServiceLocator_UlhrRhbService.php'));
}, 'App\\Controller\\AccountController:ajouterSalle' => function () {
    return ($this->privates['.service_locator.EVv_ldj'] ?? $this->load('get_ServiceLocator_EVvLdjService.php'));
}, 'App\\Controller\\FrontController:partagerSalle' => function () {
    return ($this->privates['.service_locator.FngfaY1'] ?? $this->load('get_ServiceLocator_FngfaY1Service.php'));
}, 'App\\Controller\\RegistrationController:registerAction' => function () {
    return ($this->privates['.service_locator.JPXreA6'] ?? $this->load('get_ServiceLocator_JPXreA6Service.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.UlhrRhb'] ?? $this->load('get_ServiceLocator_UlhrRhbService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
