<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.EVv_ldj.App\Entity\Jour' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.EVv_ldj": it references class "App\\Entity\\Jour" but no such service exists.');
